name: VitalSpawn
version: @version@
main: dev.meinel.leo.vitalspawn.VitalSpawn
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives you the ability to set a spawn.
commands:
  spawn:
    description: "Main command"
    usage: "/spawn"
  setspawn:
    description: "Main command"
    usage: "/setspawn"
permissions:
  vitalspawn.spawn:
    description: "Permission to teleport to spawn"
    default: op
  vitalspawn.setspawn:
    description: "Permission to set spawn"
    default: op
  vitalspawn.onspawn:
    description: "Permission to teleport to spawn on spawn"
    default: op
  vitalspawn.onrespawn:
    description: "Permission to teleport to spawn on respawn"
    default: op
  vitalspawn.delay.bypass:
    description: "Permission to bypass delay"
    default: op